# Generated by Django 4.2.7 on 2025-11-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('food', '餐饮'), ('transport', '交通'), ('shopping', '购物'), ('entertainment', '娱乐'), ('health', '医疗'), ('education', '教育'), ('housing', '住房'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预算金额')),
                ('period', models.CharField(choices=[('monthly', '月度'), ('yearly', '年度')], default='monthly', max_length=20, verbose_name='周期')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='已花费')),
                ('percentage_used', models.FloatField(default=0, verbose_name='使用百分比')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算',
                'db_table': 'budgets',
                'ordering': ['category'],
                'unique_together': {('category', 'period', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='习惯名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('target_days', models.IntegerField(default=30, verbose_name='目标天数')),
                ('reminder_enabled', models.BooleanField(default=True, verbose_name='开启提醒')),
                ('reminder_time', models.TimeField(default='09:00', verbose_name='提醒时间')),
                ('current_streak', models.IntegerField(default=0, verbose_name='当前连续天数')),
                ('longest_streak', models.IntegerField(default=0, verbose_name='最长连续天数')),
                ('total_days', models.IntegerField(default=0, verbose_name='总打卡天数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '习惯',
                'verbose_name_plural': '习惯',
                'db_table': 'habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=20, verbose_name='类型')),
                ('category', models.CharField(choices=[('food', '餐饮'), ('transport', '交通'), ('shopping', '购物'), ('entertainment', '娱乐'), ('health', '医疗'), ('education', '教育'), ('housing', '住房'), ('salary', '工资'), ('bonus', '奖金'), ('investment', '投资'), ('other', '其他')], max_length=20, verbose_name='分类')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='life_management.budget')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=100, verbose_name='快递单号')),
                ('courier', models.CharField(max_length=50, verbose_name='快递公司')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('current_status', models.CharField(max_length=100, verbose_name='当前状态')),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='最后更新')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='是否已送达')),
                ('has_exception', models.BooleanField(default=False, verbose_name='是否有异常')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '快递追踪',
                'verbose_name_plural': '快递追踪',
                'db_table': 'package_tracking',
                'unique_together': {('tracking_number', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='life_management.packagetracking')),
            ],
            options={
                'verbose_name': '快递状态',
                'verbose_name_plural': '快递状态',
                'db_table': 'package_status',
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '零食')], max_length=20, verbose_name='餐次')),
                ('description', models.TextField(verbose_name='饮食描述')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='卡路里')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/', verbose_name='图片')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('date', models.DateField(verbose_name='日期')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'meal_records',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='物品名称')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='位置')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='过期时间')),
                ('is_expired', models.BooleanField(default=False, verbose_name='是否已过期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
                'db_table': 'items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HabitRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='打卡日期')),
                ('completed', models.BooleanField(default=True, verbose_name='是否完成')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='life_management.habit')),
            ],
            options={
                'verbose_name': '习惯记录',
                'verbose_name_plural': '习惯记录',
                'db_table': 'habit_records',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
