# Generated by Django 4.2.7 on 2025-11-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('country', models.CharField(max_length=50, verbose_name='国家')),
                ('temperature', models.FloatField(verbose_name='温度(°C)')),
                ('feels_like', models.FloatField(verbose_name='体感温度(°C)')),
                ('humidity', models.IntegerField(verbose_name='湿度(%)')),
                ('pressure', models.FloatField(verbose_name='气压(hPa)')),
                ('wind_speed', models.FloatField(verbose_name='风速(m/s)')),
                ('wind_direction', models.IntegerField(verbose_name='风向(度)')),
                ('visibility', models.FloatField(blank=True, null=True, verbose_name='能见度(km)')),
                ('weather_main', models.CharField(max_length=50, verbose_name='主要天气')),
                ('weather_description', models.CharField(max_length=100, verbose_name='天气描述')),
                ('weather_icon', models.CharField(max_length=10, verbose_name='天气图标代码')),
                ('sunrise', models.DateTimeField(verbose_name='日出时间')),
                ('sunset', models.DateTimeField(verbose_name='日落时间')),
                ('data_time', models.DateTimeField(verbose_name='数据时间')),
                ('provider', models.CharField(default='openweather', max_length=50, verbose_name='数据提供商')),
                ('api_response', models.JSONField(default=dict, verbose_name='API响应原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '天气记录',
                'verbose_name_plural': '天气记录',
                'db_table': 'weather_records',
                'ordering': ['-data_time'],
            },
        ),
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_text', models.TextField(verbose_name='原文')),
                ('target_text', models.TextField(verbose_name='译文')),
                ('source_language', models.CharField(choices=[('zh', '中文'), ('en', '英语'), ('ja', '日语'), ('ko', '韩语'), ('fr', '法语'), ('de', '德语'), ('es', '西班牙语'), ('ru', '俄语')], max_length=10, verbose_name='源语言')),
                ('target_language', models.CharField(choices=[('zh', '中文'), ('en', '英语'), ('ja', '日语'), ('ko', '韩语'), ('fr', '法语'), ('de', '德语'), ('es', '西班牙语'), ('ru', '俄语')], max_length=10, verbose_name='目标语言')),
                ('provider', models.CharField(default='google', max_length=50, verbose_name='翻译服务提供商')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('api_response', models.JSONField(default=dict, verbose_name='API响应原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '翻译记录',
                'verbose_name_plural': '翻译记录',
                'db_table': 'translation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='位置名称')),
                ('description', models.TextField(blank=True, verbose_name='位置描述')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='纬度')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='经度')),
                ('address', models.TextField(verbose_name='详细地址')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('province', models.CharField(max_length=100, verbose_name='省份')),
                ('country', models.CharField(max_length=50, verbose_name='国家')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='邮政编码')),
                ('location_type', models.CharField(max_length=50, verbose_name='位置类型')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('provider', models.CharField(default='baidu', max_length=50, verbose_name='地图服务提供商')),
                ('api_response', models.JSONField(default=dict, verbose_name='API响应原始数据')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地图位置',
                'verbose_name_plural': '地图位置',
                'db_table': 'map_locations',
                'ordering': ['-created_at'],
            },
        ),
    ]
