# Generated by Django 4.2.7 on 2025-11-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='标签名称')),
                ('color', models.CharField(default='#666666', max_length=7, verbose_name='颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
                'unique_together': {('name', 'creator')},
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file', models.FileField(upload_to='resources/', verbose_name='文件')),
                ('file_type', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频'), ('other', '其他')], max_length=20, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(verbose_name='文件大小')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='resources', to='knowledge.tag')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'db_table': 'resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ocr_images/', verbose_name='图片')),
                ('recognized_text', models.TextField(verbose_name='识别文本')),
                ('confidence', models.FloatField(default=0, verbose_name='置信度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OCR结果',
                'verbose_name_plural': 'OCR结果',
                'db_table': 'ocr_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('format_type', models.CharField(choices=[('richtext', '富文本'), ('markdown', 'Markdown')], default='richtext', max_length=20, verbose_name='格式类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='notes', to='knowledge.tag')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'db_table': 'notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(verbose_name='版本号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='knowledge.note')),
            ],
            options={
                'verbose_name': '笔记版本',
                'verbose_name_plural': '笔记版本',
                'db_table': 'note_versions',
                'ordering': ['-created_at'],
                'unique_together': {('note', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='knowledge.note')),
                ('to_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='knowledge.note')),
            ],
            options={
                'verbose_name': '笔记链接',
                'verbose_name_plural': '笔记链接',
                'db_table': 'note_links',
                'unique_together': {('from_note', 'to_note')},
            },
        ),
    ]
