# Generated by Django 4.2.7 on 2025-11-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='日历名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('color', models.CharField(default='#1890ff', max_length=7, verbose_name='颜色')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日历',
                'verbose_name_plural': '日历',
                'db_table': 'calendars',
            },
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='时长（分钟）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_records', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '时间记录',
                'verbose_name_plural': '时间记录',
                'db_table': 'time_records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_duration', models.IntegerField(default=25, verbose_name='工作时长（分钟）')),
                ('break_duration', models.IntegerField(default=5, verbose_name='休息时长（分钟）')),
                ('long_break_duration', models.IntegerField(default=15, verbose_name='长休息时长（分钟）')),
                ('sessions_completed', models.IntegerField(default=0, verbose_name='已完成会话数')),
                ('current_session_type', models.CharField(choices=[('work', '工作时间'), ('break', '短休息'), ('long_break', '长休息')], default='work', max_length=20, verbose_name='当前会话类型')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '番茄钟会话',
                'verbose_name_plural': '番茄钟会话',
                'db_table': 'pomodoro_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('event_type', models.CharField(choices=[('work', '工作'), ('life', '生活'), ('health', '健康')], default='work', max_length=20, verbose_name='类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('timezone_offset', models.IntegerField(default=0, verbose_name='时区偏移（分钟）')),
                ('is_all_day', models.BooleanField(default=False, verbose_name='是否全天')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('reminder_minutes', models.IntegerField(default=15, verbose_name='提醒时间（分钟）')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='是否已提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='time_management.calendar')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日程事件',
                'verbose_name_plural': '日程事件',
                'db_table': 'events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EfficiencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='日期')),
                ('focus_hours', models.FloatField(default=0, verbose_name='专注时长（小时）')),
                ('tasks_completed', models.IntegerField(default=0, verbose_name='完成任务数')),
                ('tasks_planned', models.IntegerField(default=0, verbose_name='计划任务数')),
                ('efficiency_score', models.FloatField(default=0, verbose_name='效率评分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '效率记录',
                'verbose_name_plural': '效率记录',
                'db_table': 'efficiency_records',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
