# Generated by Django 4.2.7 on 2025-11-22 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='ocr_images/%Y/%m/', verbose_name='图片')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('extracted_text', models.TextField(blank=True, verbose_name='识别文本')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='置信度')),
                ('status', models.CharField(choices=[('pending', '待识别'), ('processing', '识别中'), ('completed', '已完成'), ('failed', '识别失败')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('ocr_provider', models.CharField(default='tesseract', max_length=50, verbose_name='OCR提供商')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OCR识别记录',
                'verbose_name_plural': 'OCR识别记录',
                'db_table': 'ocr_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
